### ISSUE TITLE
How to disable Zoom?

### ISSUE THREAD

**Issue by Cloudmersive** [vasturiano/globe.gl#61] opened 2021-07-17 22:59 UTC
There seems to be no way to disable Zoom (scroll wheel causing zoom in/out) - any help with this would be appreciated

**Comment by vasturiano** [comment] 2021-07-18 22:44
Duplicate of https://github.com/vasturiano/globe.gl/issues/34#issuecomment-881968776

**Closed by vasturiano** 2021-07-18 22:44 UTC
